Sample Datasets Preperation

In [5]:
import numpy as np
from sklearn import preprocessing

sampleData = np.array([[1.6, 2.3, -5.7],
                       [-5.6, 5.4, 3.2],
                       [4.2, -3.3, -5.2],
                       [1.4, 2.7, 3.5]])

sampleData.shape

(4, 3)

First Technique (Binarization)

In [10]:
preprocessor = preprocessing.Binarizer(threshold=0.5)
binarizedData = preprocessor.transform(sampleData)
binarizedData

array([[1., 1., 0.],
       [0., 1., 1.],
       [1., 0., 0.],
       [1., 1., 1.]])

Second Techique (Scalling)

In [16]:
preprocessor = preprocessing.MinMaxScaler(feature_range=(0, 1))
scaledData= preprocessor.fit_transform(sampleData)
scaledData

array([[0.73469388, 0.64367816, 0.        ],
       [0.        , 1.        , 0.9673913 ],
       [1.        , 0.        , 0.05434783],
       [0.71428571, 0.68965517, 1.        ]])

Third Technique Pt1 (L1: Least Absolut Deviation)

In [18]:
sampleData

array([[ 1.6,  2.3, -5.7],
       [-5.6,  5.4,  3.2],
       [ 4.2, -3.3, -5.2],
       [ 1.4,  2.7,  3.5]])

In [24]:
L1Normalised = preprocessing.normalize(sampleData, norm='l1')
L1Normalised

array([[ 0.16666667,  0.23958333, -0.59375   ],
       [-0.3943662 ,  0.38028169,  0.22535211],
       [ 0.33070866, -0.25984252, -0.40944882],
       [ 0.18421053,  0.35526316,  0.46052632]])

Third Technique Pt1 (L2: Least Square)

In [26]:
sampleData

array([[ 1.6,  2.3, -5.7],
       [-5.6,  5.4,  3.2],
       [ 4.2, -3.3, -5.2],
       [ 1.4,  2.7,  3.5]])

In [27]:
L2Normalised = preprocessing.normalize(sampleData, norm='l2')
L2Normalised

array([[ 0.25191384,  0.36212615, -0.89744307],
       [-0.66572385,  0.641948  ,  0.38041363],
       [ 0.56341589, -0.44268391, -0.69756253],
       [ 0.30193176,  0.58229698,  0.75482941]])